spring:
  data:
    mongodb:
      username: kevin
      password: kevin
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*' # Just for development, specify packages in production
        spring.json.type.mapping: orderConfirmation:com.kevin.order.kafka.OrderConfirmation, paymentConfirmation:com.kevin.payment.notification.PaymentNotificationRequest
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040
